version: '3.1'

networks:
  docker_net:
    ipam:
      driver: default
      config:
        - subnet: 172.6.0.0/16
        
volumes:
  jenkins_data:
    driver: local
    
services:
  zabbix_server:
    build: zabbix_server
    image: zabbix_server
    container_name: zabbix_server
    hostname: zabbix_server
    networks:
      docker_net:
        ipv4_address: 172.6.0.2
    ports: 
      - 10051:10051
    restart: always
  
  zabbix_front:
    build: zabbix_front
    image: zabbix_front
    container_name: zabbix_front
    hostname: zabbix_front
    networks:
      docker_net:
        ipv4_address: 172.6.0.3
    ports:
      - 81:80
    depends_on: 
      - zabbix_server
    restart: always
  
  zabbix_agent:
    build: zabbix_agent
    image: zabbix_agent
    container_name: zabbix_agent
    hostname: zabbix_agent
    network_mode: "host"
    ports: 
      - 10050:10050
    privileged: true
    depends_on: 
      - zabbix_server
    restart: always
  
  grafana:
    build: grafana
    image: grafana
    container_name: grafana
    hostname: grafana
    networks:
        docker_net:
          ipv4_address: 172.6.0.4
    ports: 
      - 82:8443
    volumes:
      - ./grafana/files/grafana.repo:/etc/yum.repos.d/grafana.repo:rw
      - ./grafana/files/grafana.ini:/etc/grafana/grafana.ini:rw

  jenkins:
    image: "jenkins/jenkins:lts"
    container_name: jenkins
    hostname: jenkins
    networks:
      docker_net:
        ipv4_address: 172.6.0.5
    ports:
      - 83:8080
      - 443:8443
      - 50000:50000
    volumes:
      - jenkins_data:/jenkins_config
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock